'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

def fibGen():
    a, b = 1, 1
    while True:
        yield a
        b, a = a, a + b
        

def sumEvenFib(limit):
    evenSum = 0
    for n in fibGen():
        if n > limit:
            return evenSum
        if n % 2 == 0:
            evenSum += n


print sumEvenFib(4000000)
