'''
Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle        T_n=n(n+1)/2        1, 3, 6, 10, 15, ...
Pentagonal      P_n=n(3n-1)/2       1, 5, 12, 22, 35, ...
Hexagonal       H_n=n(2n-1)         1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
'''

def triangle(n):
    return n * (n + 1) / 2

def pentagonal(n):
    return n * (3 * n - 1) / 2

def hexagonal(n):
    return n * (2 * n - 1)


def isTriangle(v):
    cv = triangle(n['t'])
    while cv < v:
        n['t'] += 1
        cv = triangle(n['t'])
    return cv == v

def isPentagonal(v):
    cv = pentagonal(n['p'])
    while cv < v:
        n['p'] += 1
        cv = pentagonal(n['p'])
    return cv == v


n = {'t': 285, 'p': 165, 'h': 144}

while True:
    v_h = hexagonal(n['h'])
    if isTriangle(v_h) and isPentagonal(v_h):
        print triangle(n['t'])
        break
    else:
        n['h'] += 1
