'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	T(n)=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	P(n)=n(3n1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	H(n)=n(2n1)	 	1, 6, 15, 28, 45, ...

It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''
def triangle(n):
    return n*(n+1)/2
def pentagonal(n):
    return n*(3*n-1)/2
def hexagonal(n):
    return n*(2*n-1)



i_t = 286
i_p = 165
i_h = 143

valueFound = False
while not valueFound:
    targetValue = triangle(i_t)
    tempPResult = pentagonal(i_p)
    if tempPResult == targetValue:
        while True:
            tempHResult = hexagonal(i_h)
            if tempHResult == tempPResult:
                valueFound = True
            if tempHResult < tempPResult:
                i_h += 1
            else:
                break
    if tempPResult < targetValue:
        i_p += 1
    else:
        i_t += 1
print targetValue
